config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'posts/index'
  get 'posts/new', to: 'posts#new'
  
  get 'posts/:id', to: 'posts#show', constraints: { id: /\d+/ }
  get 'posts/:topic', to: 'posts#topic'

  post 'posts/create', to: 'posts#create'
  get 'posts/edit/:id', to: 'posts#edit'
  post 'posts/update/:id', to: 'posts#update'

  get 'posts', to: 'posts#index'

  post 'comments/create/:post_id', to: 'comments#create', constraints: { post_id: /\d+/ }
  post 'comments/create/:post_id/replies/:parent_id', to: 'comments#create', constraints: { post_id: /\d+/, parent_id: /\d+/ }

  root to: "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :body, presence: true, length: { minimum: 10, maximum: 2000 }

  def self.comments_for_post(post_id)
    # SELECT "comments".* FROM "comments" WHERE (post_id = 20 and parent_id = 0) ORDER BY id
    Comment.where("post_id = ? and parent_id = 0", post_id).order("id")
  end

  def self.replies_for_post(post_id)
    # SELECT "comments".* FROM "comments" WHERE (post_id = 20 and parent_id != 0) ORDER BY parent_id, id
    Comment.where("post_id = ? and parent_id != 0", post_id).order(["parent_id", "id"]).group_by { |comment| comment["parent_id"] }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_rich_text :body

  validates :title, presence: true, length: { maximum: 300 }
  validates :body, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, authentication_keys: [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params.permit(:body, :post_id, :parent_id))
    unless params[:parent_id].present?
      @comment.parent_id = 0
    end
    @comment.save
    render :json => { comment: @comment, errors: @comment.errors }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  Max_page_size = 3

  def index
    page_token = params.has_key?(:older) ? params[:older] : params[:newer]

    paginate(page_token)
  end

  def topic
    page_token = params.has_key?(:older) ? params[:older] : params[:newer]

    @topic = Topic.find_by(alias: params[:topic])
    paginate(page_token, @topic.id)

    render 'index'
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.comments_for_post(@post.id)
    @replies = Comment.replies_for_post(@post.id)
  end

  def edit
    @topics = Topic.all()
    @post = Post.find(params[:id])
  end

  def new
    @topics = Topic.all()
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to '/posts/' + @post.id.to_s
    else
      @topics = Topic.all()
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to '/posts/' + @post.id.to_s
    else
      @topics = Topic.all()
      render 'edit'
    end
  end

  private

  def post_params
    params[:post][:topic_id] = params[:post][:topic]
    params[:post][:user_id] = params[:post][:user]
    params.require(:post).permit(:title, :body, :topic_id, :user_id)
  end

  def paginate(page_token, topic_id = nil)
    pagination = Services::Pagination.new(page_token, topic_id)

    if page_token.present?
      if params.has_key?(:newer)
        @posts = pagination.newer
      else
        @posts = pagination.older
      end
    else
      @posts = pagination.first_page
    end

    @has_newer = pagination.has_newer
    @has_older = pagination.has_older

    @page_token = pagination.construct_page_token
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRailsReact</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Хабрахабр</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/posts/development">Разработка</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/posts/administration">Администрирование</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/posts/design">Дизайн</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/posts/management">Менеджмент</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/posts/marketing">Маркетинг</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/posts/science">Научпоп</a>
            </li>
            <%# <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li> %>
          </ul>
          <ul class="navbar-nav ml-auto">
            <div>
              <% if user_signed_in? %>
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                  <%= link_to 'Новый пост', posts_new_path, class:"btn btn-light border" %>

                  <div class="btn-group" role="group">
                    <button id="btnGroupDrop1" type="button" class="btn btn-light border dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <%= current_user.username %>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                      <%= link_to 'Изменить профиль', edit_user_registration_path, class:"dropdown-item" %>
                      <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class:"dropdown-item" %>
                    </div>
                  </div>
                </div>
                
                
              <% else %>
                <%= link_to 'Регистрация', new_user_registration_path, class:"btn btn-primary" %>
                <%= link_to 'Войти', new_user_session_path, class:"btn btn-dark" %>
              <% end %>
            </div>
          </ul>
        </div>
      </div>
    </nav>
  
    
      
        

    <div class="row">
      <div class="col-md-8">

        <% if notice.present?  %>
          <div class="alert alert-success" role="alert">
            <%= notice %>
          </div>
        <% elsif alert.present? %>
          <div class="alert alert-danger" role="alert">
            <%= alert %>
          </div>
        <% end %>

        <%= yield %>

      </div>

      

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-0">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<h3>Новый Пост</h1>

<% if @post.present? %>
  <% @post.errors.each do |attr, msg| %>
    <div class="alert alert-danger" role="alert">
      <%= msg %>
    </div>
  <% end %>
<% end %>

<%= form_for(:post, url: path, method: "post") do %>
  <%= hidden_field(:post, :user, value: current_user.id) %>
  <div class="form-grop mt-3">
    <%= label(:post, :title, "Заголовок") %>
    <%= text_field(:post, :title, class: "form-control") %>
  </div>

  <div class="form-grop mt-3">
    <%= label(:post, :topic, "Выберите тему") %>
    <%= select(:post, :topic, options_from_collection_for_select(@topics, "id", "title", @post.present? ? @post.id : nil ), {}, {class: "form-control"}) %>
  </div>

  <div class="form-group mt-3">
    <%= label(:post, :body, "Текст") %>
    <%= rich_text_area(:post, :body, class: "form-control", rows: "10") %>
  </div>

  <div class="form-group mt-3">
    <%= submit_tag(action == "edit" ? "Сохранить" : "Создать", class: "btn btn-primary") %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render partial: "form", locals: { path: "/posts/update/#{@post.id}", action: "edit" } %>
  

app/views/posts/index.html.erb
<!-- Blog Entries Column -->

<h3 class="my-4">
<% if @topic == nil %>
Все посты
<% else %>
<%= @topic.title %>
<% end %>
</h1>

<% @posts.each do |post| %>
<!-- Blog Post -->
<div class="card mb-4">
  <div class="card-body">
    <h2 class="card-title"><%= post.title %></h2>
    <p class="card-text"><%= truncate(post.body.to_plain_text , length: 300, omission: '...') %></p>
    <a href="/posts/<%= post.id %>" class="btn btn-primary">Читать дальше &rarr;</a>
  </div>
  <div class="card-footer text-muted">
    Posted on <%= post.created_at %>
  </div>
</div>
<% end %>

<!-- Pagination -->
<ul class="pagination justify-content-center mb-4">
  <li class="page-item <% unless @has_newer %> disabled <% end %> ">
    <a class="page-link" href="/posts/<% if @topic.present? %><%= @topic.alias %><% end %>?newer=<%= @page_token %>">&larr; Более новые</a>
  </li>
  <li class="page-item <% unless @has_older %> disabled <% end %> ">
    <a class="page-link" href="/posts/<% if @topic.present? %><%= @topic.alias %><% end %>?older=<%= @page_token %>">Более старые &rarr;</a>
  </li>
</ul>

app/views/posts/new.html.erb
<%= render partial: "form", locals: { path: "/posts/create", action: "new" } %>
  

app/views/posts/show.html.erb
<!-- Post Content Column -->

<!-- Title -->
<h3 class="mt-4"><%= @post.title %></h1>

<!-- Author -->
<p class="lead"><%= @post.user.username %>
</p>

<hr>

<!-- Date/Time -->
<p>Posted on <%= @post.created_at %></p>

<hr>

<!-- Post Content -->
<%= @post.body %>
<hr>

<!-- Comments Form -->
<%= react_component("CommentsApp", { comments: @comments, replies: @replies, csrf_token: form_authenticity_token, post_id: @post.id }) %>